"""empty message

Revision ID: 1548ddcee220
Revises: 7652903db8c4
Create Date: 2021-11-04 13:42:27.474242

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1548ddcee220"
down_revision = "7652903db8c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("roster", sa.String(), nullable=True))
    op.add_column("contacts", sa.Column("location", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "location")
    op.drop_column("contacts", "roster")
    # ### end Alembic commands ###
