"""empty message

Revision ID: 19e1a065abf9
Revises: 69bbc709449c
Create Date: 2022-05-01 22:55:01.340804

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "19e1a065abf9"
down_revision = "69bbc709449c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
