"""empty message

Revision ID: 451d35519a9b
Revises: daab6d39a371
Create Date: 2021-11-05 11:09:41.549899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451d35519a9b'
down_revision = 'daab6d39a371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_genre_id_fkey', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('contacts_genre_id_fkey', 'contacts', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
