"""empty message

Revision ID: 69bbc709449c
Revises: 012d1298a8f1
Create Date: 2022-05-01 22:51:35.710354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69bbc709449c"
down_revision = "012d1298a8f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_addresses", sa.Column("command_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "email_addresses", sa.Column("email_type_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "email_addresses", "commands", ["command_id"], ["id"])
    op.create_foreign_key(
        None, "email_addresses", "email_types", ["email_type_id"], ["id"]
    )
    op.drop_constraint("email_types_command_id_fkey", "email_types", type_="foreignkey")
    op.drop_constraint(
        "email_types_email_type_id_fkey", "email_types", type_="foreignkey"
    )
    op.drop_column("email_types", "command_id")
    op.drop_column("email_types", "email_type_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_types",
        sa.Column("email_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "email_types",
        sa.Column("command_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "email_types_email_type_id_fkey",
        "email_types",
        "email_types",
        ["email_type_id"],
        ["id"],
    )
    op.create_foreign_key(
        "email_types_command_id_fkey", "email_types", "commands", ["command_id"], ["id"]
    )
    op.drop_constraint(None, "email_addresses", type_="foreignkey")
    op.drop_constraint(None, "email_addresses", type_="foreignkey")
    op.drop_column("email_addresses", "email_type_id")
    op.drop_column("email_addresses", "command_id")
    # ### end Alembic commands ###
