"""empty message

Revision ID: 7be068fa4a58
Revises: 8b173d9a1c1d
Create Date: 2021-11-06 22:18:27.450131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be068fa4a58'
down_revision = '8b173d9a1c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster',
    sa.Column('Roster ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Contact ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Contact ID'], ['contacts.id'], name='roster_Contact ID_fkey'),
    sa.ForeignKeyConstraint(['Roster ID'], ['rosters.id'], name='roster_Roster ID_fkey'),
    sa.PrimaryKeyConstraint('Roster ID', 'Contact ID', name='roster_pkey')
    )
    # ### end Alembic commands ###
