"""empty message

Revision ID: d3692e29f7eb
Revises: 0263699f6966
Create Date: 2022-05-01 19:43:33.630681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3692e29f7eb"
down_revision = "0263699f6966"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
