"""empty message

Revision ID: d44751cbc976
Revises: 709cb05a65dd
Create Date: 2021-11-07 11:12:33.725873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44751cbc976'
down_revision = '709cb05a65dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rosters_id', table_name='rosters')
    op.drop_table('rosters')
    op.drop_table('roster_rel')
    op.add_column('contacts', sa.Column('command', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('email_type', sa.String(), nullable=True))
    op.drop_column('contacts', 'roster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('roster', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'email_type')
    op.drop_column('contacts', 'command')
    op.create_table('roster_rel',
    sa.Column('Roster ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Contact ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Contact ID'], ['contacts.id'], name='roster_rel_Contact ID_fkey'),
    sa.ForeignKeyConstraint(['Roster ID'], ['rosters.id'], name='roster_rel_Roster ID_fkey'),
    sa.PrimaryKeyConstraint('Roster ID', 'Contact ID', name='roster_rel_pkey')
    )
    op.create_table('rosters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rosters_pkey')
    )
    op.create_index('ix_rosters_id', 'rosters', ['id'], unique=False)
    # ### end Alembic commands ###
