"""empty message

Revision ID: daab6d39a371
Revises: 1548ddcee220
Create Date: 2021-11-05 11:08:46.498957

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "daab6d39a371"
down_revision = "1548ddcee220"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
