"""empty message

Revision ID: fa9675515ea6
Revises: 19e1a065abf9
Create Date: 2022-05-01 22:55:47.952899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa9675515ea6"
down_revision = "19e1a065abf9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
